spring.application.name=mobile-banking-FS

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile-banking-FS
spring.datasource.username=postgres
spring.datasource.password=tongbora

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# security config
#spring.security.user.name=tongbora
#spring.security.user.password=qwer

# config jwt decoder
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/mbapi

media.server-path=D:/Server/Full-Stack-M/
media.client-path=/media/**
media.base-uri=http://localhost:8080/media/

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
